/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 18-Oct-2017 11:58:32 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[Categories]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[Categories]
GO

/* Create Tables */

CREATE TABLE [dbo].[Categories]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[name] varchar(255) NOT NULL,
	[title] varchar(255) NOT NULL,
	[desc] varchar(255) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[Categories] 
 ADD CONSTRAINT [PK_Categories]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO
