/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Oct-2017 12:18:37 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[Description]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[Description]
GO

/* Create Tables */

CREATE TABLE [dbo].[Description]
(
	[id] bigint NOT NULL,
	[phonetic_id] bigint NOT NULL,
	[desc] varchar(255) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[Description] 
 ADD CONSTRAINT [PK_Description]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO
