/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Oct-2017 12:19:44 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[Examples]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[Examples]
GO

/* Create Tables */

CREATE TABLE [dbo].[Examples]
(
	[id] bigint NOT NULL,
	[description_id] bigint NOT NULL,
	[example] varchar(1024) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[Examples] 
 ADD CONSTRAINT [PK_Examples]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO
