/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Oct-2017 12:22:36 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[Favorites]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[Favorites]
GO

/* Create Tables */

CREATE TABLE [dbo].[Favorites]
(
	[id] bigint NOT NULL,
	[vocabulary_id] bigint NOT NULL,
	[user_id] bigint NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[Favorites] 
 ADD CONSTRAINT [PK_Favorites]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO
