/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Oct-2017 12:21:06 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[Translation]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[Translation]
GO

/* Create Tables */

CREATE TABLE [dbo].[Translation]
(
	[id] bigint NOT NULL,
	[example_id] bigint NOT NULL,
	[translation] varchar(1024) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[Translation] 
 ADD CONSTRAINT [PK_Translation]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO
