/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 18-Oct-2017 11:56:52 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[Users]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[Users]
GO

/* Create Tables */

CREATE TABLE [dbo].[Users]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[name] varchar(255) NOT NULL,
	[first_name] varchar(50) NOT NULL,
	[midle_name] varchar(50) NULL,
	[last_name] varchar(50) NOT NULL,
	[email] varchar(255) NULL,
	[birth_day] smallint NULL,
	[birth_month] smallint NULL,
	[birth_year] int NULL,
	[created_time] timestamp NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[Users] 
 ADD CONSTRAINT [PK_Users]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO
