/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Oct-2017 12:01:03 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[Vocabularies]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[Vocabularies]
GO

/* Create Tables */

CREATE TABLE [dbo].[Vocabularies]
(
	[id] bigint NOT NULL,
	[name] varchar(255) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[Vocabularies] 
 ADD CONSTRAINT [PK_Vocabularies]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO
